config/routes.rb
Nomster::Application.routes.draw do
  devise_for :users
  root 'places#index'
  resources :places do 
    resources :comments, only: :create
    resources :photos, only: :create
  end 

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user
	belongs_to :place

	 RATINGS = {
    'one star'    => '1_star',
    'two stars'   => '2_stars',
    'three stars' => '3_stars',
    'four stars'  => '4_stars',
    'five stars'  => '5_stars'
  }
def humanized_rating
    RATINGS.invert[self.rating]
end
	
end

app/models/photo.rb
class Photo < ActiveRecord::Base
	belongs_to :user 
	belongs_to :place
	mount_uploader :picture, PictureUploader
end

app/models/place.rb
class Place < ActiveRecord::Base
	belongs_to :user
	has_many :comments
	has_many :photos

	# For map API
	geocoded_by :address 
	after_validation :geocode  

	#Validations
	validates :name,  presence: true, length: {minimum: 3}
	validates :address, presence: true
	validates :description, presence: true 


	 
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :places
  has_many :comments
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :authenticate_user!
	def create
		@place = Place.find(params[:place_id])
		@place.comments.create(comment_params.merge(user: current_user))
		redirect_to place_path(@place)
	end 


private

	def comment_params
  		params.require(:comment).permit(:message, :rating)
  	end	
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
	

	def create 
		@place = Place.find(params[:place_id])
		@place.photos.create(photo_params.merge(user: current_user))
		redirect_to place_path(@place)
	end

	private 

	def photo_params
		params.require(:photo).permit(:caption, :picture)
	end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
	before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

        #  -----INDEX-----------
        #  @var =  model name .all unless using .paginate 
        #  Has its own page
	def index
		@places = Place.paginate(page:params[:page], per_page: 3)
	end

		#  -----NEW-------------
		#  @var = model name . new
		#  Has its own page
		#  Has form 
	def new
		@place = Place.new
	end
		#  -----CREATE----------
		#  Submits data to database
		#  @var = model name . create unless using devise
		#  divise change to current_user.places.create(place_params)
	def create
		@place = current_user.places.create(place_params)
		if @place.valid?
			redirect_to root_path
		else 
			render :new, status: :unprocessable_entity
		end
		
	end

		#  -----SHOW------------
		#  Find the right place and include (params[:id])
	def show
		@place = Place.find(params[:id])
		@comment = Comment.new
		@photo = Photo.new 
	end


		#  -----EDIT------------
		#  Find the right place and include (params[:id])
	def edit
		@place = Place.find(params[:id])

		if @place.user != current_user 
			return render text: 'Error: Access prohibited!', status: :forbidden 
		end
	end


		#  -----UPDATE----------
		#  Find the right place and include (params[:id])
		#  Update this record and save the changes the user specifies into our database.
		#  Redirect User to root
	def update
		@place = Place.find(params[:id])
		if @place.user != current_user 
			return render text: 'Error: Access prohibited!', status: :forbidden 
		end
		@place.update_attributes(place_params)
		if @place.valid?
           redirect_to root_path
        else
           render :edit, status: :unprocessable_entity
        end
	end	


        # -----DESTROY---------
	    # Find the right place
	    # Destroy the place from our database
	    # Redirect User to root
	def destroy
		@place = Place.find(params[:id])
		if @place.user != current_user 
			return render text: 'Error: Access prohibited!', status: :forbidden 
		end
		@place.destroy
		redirect_to root_path
		
	end

	private

        #-----PARAMS------------
        #  Require (file)  Permit (Rows)
        #  Sucks code from form and puts it in database
	def place_params
		params.require(:place).permit(:name, :description, :address)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Nomster</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<body>

<nav class="navbar navbar-inverse" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
     
      <%= link_to image_tag("https://cdn2.iconfinder.com/data/icons/windows-8-metro-style/32/beer.png"), root_path, class: 'navbar-brand' %>
     
      <%= link_to 'Draft & Craft', root_path, class: 'navbar-text' %> 
      
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
       <li>
        <%= link_to new_place_path do %> 
        <i class="glyphicon glyphicon-plus-sign"></i>
        New Place
        <% end %>
       </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
         <li> <%= link_to 'Sign Out', destroy_user_session_path, method: :delete%>
        
        </li>
        <% else %>
        <li><%= link_to 'Sign In', new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
</nav>
        <% if notice.present? %>
        <p class="alert alert-info"><%= notice %></p>
        <% end %>
        <% if alert.present? %>
        <p class="alert alert-danger"><%= alert %></p>
        <% end %>
  </div>


<%= yield %>

</body>
</html>

app/views/places/edit.html.erb
<div class="detail-box col-xs-12 col-sm-8 col-sm-offset-2">
	<div class="panel panel-default">
		<div class="panel-heading">		
		<h1> Edit Your Place </h1>
		</div>

		<div class="panel-body">
		<%= simple_form_for @place do |f| %>
			<%= f.input :name %>
			<%= f.input :address %>
			<%= f.input :description %>
			<br />
			<%= f.submit 'Update', class: 'btn btn-primary' %>
		<% end %>
		</div>
	</div>	
</div>	

app/views/places/index.html.erb
	
<!--Places panels -->
<% @places.each do |place| %>
    <div class="detail-box col-xs-12 col-sm-10 col-sm-offset-1" >
		<div class="panel panel-default">

			<div class="panel-heading">

				<h1><%= link_to place.name, place_path(place) %></h1>
			</div>	


				<div class="panel-body">
				  <div class="address col-xs-12 col-sm-4">
						<h4> Address:</h4>		
						<p><%= place.address %></p>
				  </div>
				  		<div class="clear"><br /></div>
						<div class="pic-box col-xs-12 col-sm-8 col-sm-offset-2">
						<% if place.photos.last.present? && place.photos.last.picture.present? %>
						<%= image_tag place.photos.last.picture, :class => 'img-responsive', :style => "max-height:350px" %>
						<% end %>
						</div>
						

						<div class="clear"</div>
							<br />
							<div class="description col-xs-12 col-sm-6">
							<h4>Description:</h4>
							<p><%= place.description %></p> <br />
							</div>
						 

		    				<% if place.comments.present? %>
							  <div class="col-xs-12">
							  	<div class="comment_box">
							  	<h2 class= "index_comment"> Last Comment:</h2>
							  </div>

							    <blockquote>
							      <% if place.comments.last.humanized_rating.present? %>
							        <b><%= place.comments.last.humanized_rating %></b> -
							      <% end %>
							      <%= place.comments.last.message %>
							      <small><%= place.comments.last.user.email %></small>
							    </blockquote>
							  </div>
							<% end %>
				  	
				</div>	

	    </div>	
    </div>
<% end %>	 


<!--Pagination -->		
		<div class="text-center">
			<ul class="pagination">
				<%= will_paginate @places, renderer: BootstrapPagination::Rails %>
			</ul>		    
		</div>

app/views/places/new.html.erb
<div class="detail-box col-xs-12 col-sm-8 col-sm-offset-2">
	<div class="panel panel-default">
			<div class="panel-heading">
			<h1> Enter Your Place Details </h1>
			</div>
			<div class="panel-body"> 
			<%= simple_form_for @place do |f| %>
			    <%= f.input :name %> 
			    <%= f.input :address %> 
			    <%= f.input :description %>
			    <br />
			    <%= f.submit 'Create', class:'btn btn-primary' %>
			</div>
	<% end %>    
	</div>
</div>	

app/views/places/show.html.erb
     <!-- Places Box -->

<div class="detail-box col-xs-12 col-sm-10 col-sm-offset-1 "> 	
 	<div class="panel panel-default">				

		<div class="panel-heading">
			<h1><%= @place.name %></h1>
		</div>
		<div class="panel-body">
  
       <!-- Photo -->

        <div class='place_box col-xs-12 col-sm-6'>
          <h4>Address:</h4>   
          <p><%= @place.address %></p>
          

        <% if @place.photos.present? %>
         <% @place.photos.each do |photo| %>
            <%= image_tag photo.picture, :class => 'img-responsive' %>
             <i> Caption: <%= photo.caption %></i><br />
          <% end %>
        <% end %>
        
        </div>
        <br />

        




        <!-- Map API --> 

  			<!DOCTYPE html>
        <div class="map col-xs-12 col-sm-6">
         
          
            <html>
              <head>
                <meta name="viewport" content="initial-scale=1.0, user-scalable=no">
                <meta charset="utf-8">
                <title>Simple markers</title>
              </head>  
              <body> 
                <% if @place.latitude.present? && @place.longitude.present? %>  
                <script>
                var marker;
                function initMap() {
              
                var myLatLng = {lat: <%= @place.latitude %>, lng: <%= @place.longitude %>};

                var map = new google.maps.Map(document.getElementById('map'), {
                  zoom: 12,
                  center: myLatLng
                });

              
                  marker = new google.maps.Marker({
                  position: myLatLng,
                  draggable: false,
                  animation: google.maps.Animation.DROP,
                  map: map,
                  title: 'Hello World!'
                });
                  marker.addListener('click', toggleBounce);
                }
                function toggleBounce() {
                  if (marker.getAnimation() !== null) {
                    marker.setAnimation(null);
                  } else {
                    marker.setAnimation(google.maps.Animation.BOUNCE);
                  }
                }

                </script>
                <div id="map"></div>
                <% end %>

                <br />
               
                <script async defer
                    src="https://maps.googleapis.com/maps/api/js?signed_in=true&callback=initMap"></script>
              </body>
            </html>
          
            <div class="caption pull-left col-xs-12">
            
            <h4>Description:</h4>
            <p><%= @place.description %></p>

            </div> 
            <!-- Place Edit and Delete Button -->
            
              <div class="pull-right">
                <% if current_user && current_user == @place.user %>


                <div class="btn btn-primary" data-toggle="modal" data-target="#addPhotoModal">
                      Add a photo
                </div>  

                <%= link_to 'Edit', edit_place_path(@place), class: 'btn btn-primary' %>
                  
                <%= link_to 'Delete', place_path(@place), method: :delete, data: {confirm: 'Are you sure you want to delete this?'}, class: 'btn btn-danger' %>
                <% end %>
              </div>




        </div>
         <div class="clear"></div>








                   <div class="clear"></div>
          <br />
          
    </div>
  </div>    








    <!-- Comment Box -->

    <div class=" panel-body comments col-xs-12">   
        <div class="comment_header col-xs-12">

          <div class="panel-body comment_title_box col-xs-12">
              <div class='title_box'>
              <h1 class="big_comment">Comments
              <img src="https://cdn3.iconfinder.com/data/icons/simple-microphone-icon/512/Comment_Icon-2-64.png" > 
              <br />
              </div>
          </div> 

          <br />


              <div class="comment_button col-xs-12">
              <button class="btn btn-primary pull-right add_a_comment" data-toggle="modal" data-target="#myModal">
                Leave a Comment!
              </button>
        </div></h1>
    </div>
             
              <div class="clear"></div>
            <% @place.comments.each do |comment| %>
            <div class="col-xs-12">
              <blockquote>
                <% if comment.humanized_rating.present? %>
                <b><%= comment.humanized_rating %></b> -
                <% end %>
                   <%= comment.message %>
                <small><%= comment.user.email %></small>
              </blockquote>
            </div>
            <% end %>


        <div class="clear"></div>






        <!-- Photo Modal -->

      <div class="modal fade" id="addPhotoModal" tabindex="-1" role="dialog" aria-labelledby="AddPhotoLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
              <h3 class="modal-title" id="myModalLabel">Add a Photo</h3>
            </div>

            <%= simple_form_for @photo, url: place_photos_path(@place) do |f| %>

            <div class="modal-body">
              <div class="clear"></div>
          
            <%= f.input :picture %>
            <%= f.input :caption %>
          
            </div>
            <div class="modal-footer">
              
             <%= f.submit "Add Photo", class: 'btn btn-primary' %>

            </div>
            <% end %>
          </div>
        </div>
      </div>  


      <!-- Comment Modal -->

      <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
              <h3 class="modal-title" id="myModalLabel">Add a Comment</h3>
            </div>

            <%= simple_form_for @comment, url: place_comments_path(@place) do |f| %>

            <div class="modal-body">
              <div class="clear"></div>
          
            <%= f.input :message %>
            <%= f.input :rating, as: :select, collection: Comment::RATINGS %><br />
          
            </div>
            <div class="modal-footer">
              
             <%= f.submit "Submit Comment", class: 'btn btn-primary' %>

            </div>
            <% end %>
          </div>
        </div>
      </div> 

      
</div>

   
		
	
 